### ISSUE TITLE
fails on non_std thumbv7em-none-eabihf target

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LoliGothick/clippy-check#94]
```yml
  clippy_pybadge:
    runs-on: ubuntu-latest
    needs: [test_pc, check_pybadge]
    steps:
        - name: Install alsa, libudev
          run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev
        - uses: actions/checkout@v2
        - uses: dtolnay/rust-toolchain@stable
          id: "rust-toolchain"
          with:
            components: clippy
            targets: thumbv7em-none-eabihf
        - uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/git
              ~/.cargo/registry
              target
            key: "Clippy ${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
        - uses: LoliGothick/clippy-check@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            working-directory: pybadge
```
Looks like this action does still try to check for `x86_64-unknown-linux-gnu` even if `thumbv7em-none-eabihf` is the default toolchain and and `thumbv7em-none-eabihf` is set in the `.cargo/config.toml`.
https://github.com/LuckyTurtleDev/m3/actions/runs/5079399727/jobs/9125123200#step:6:229
```json
  {"reason":"compiler-message","package_id":"m3-pybadge 0.1.0 (path+file:///home/runner/work/m3/m3/pybadge)","manifest_path":"/home/runner/work/m3/m3/pybadge/Cargo.toml","target":{"kind":["bin"],"crate_types":["bin"],"name":"m3-pybadge","src_path":"/home/runner/work/m3/m3/pybadge/src/main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"message":{"rendered":"error: language item required, but not found: `eh_personality`\n  |\n  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library\n  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`\n\n","children":[{"children":[],"code":null,"level":"note","message":"this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`","rendered":null,"spans":[]}],"code":null,"level":"error","message":"language item required, but not found: `eh_personality`","spans":[]}}
```

see: https://github.com/LuckyTurtleDev/m3/pull/34

Running `cargo clippy` in the pybadge directory manual does work fine.
